package migrate

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/anthropics/lingtai-tui/internal/preset"
)

var defaultPresetSkillsPaths = []interface{}{
	"../.library_shared",
	"~/.lingtai-tui/utilities",
}

// migratePresetSkillsPaths repairs saved presets affected by the preset editor
// model-switch bug fixed in PR #312. Those presets can keep their optional
// capabilities (web_search/vision) but silently lose the skills capability entry
// whose paths kwarg is the only place the global utility shelf and shared
// network shelf are recorded.
//
// Scope: global saved presets only. Built-in templates are regenerated by the
// TUI and already include the default skills paths. Agent init.json-only edits
// are not durable because active presets rematerialize capabilities at boot.
//
// Idempotent: existing skills.paths values are preserved exactly; missing paths
// are added with the same defaults emitted by preset.skillsDefault().
func migratePresetSkillsPaths(_ string) error {
	presetsDir := preset.PresetsDir()
	savedDir := filepath.Join(presetsDir, "saved")
	return filepath.WalkDir(savedDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return err
		}
		if d == nil || d.IsDir() {
			return nil
		}
		name := d.Name()
		ext := filepath.Ext(name)
		if (ext != ".json" && ext != ".jsonc") || strings.HasPrefix(name, "_") {
			return nil
		}
		patchPresetSkillsPathsFile(path)
		return nil
	})
}

func patchPresetSkillsPathsFile(path string) {
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var doc map[string]interface{}
	if err := json.Unmarshal(data, &doc); err != nil {
		fmt.Fprintf(os.Stderr, "m037: skipping preset %s — unparseable: %v\n", path, err)
		return
	}
	manifest, ok := doc["manifest"].(map[string]interface{})
	if !ok {
		return
	}
	caps, ok := manifest["capabilities"].(map[string]interface{})
	if !ok {
		if _, exists := manifest["capabilities"]; exists {
			return
		}
		caps = map[string]interface{}{}
		manifest["capabilities"] = caps
	}
	if !patchPresetSkillsPathsMap(caps) {
		return
	}
	updated, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "m037: marshal failed for %s: %v\n", path, err)
		return
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, updated, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "m037: write tmp failed for %s: %v\n", path, err)
		return
	}
	if err := os.Rename(tmp, path); err != nil {
		fmt.Fprintf(os.Stderr, "m037: rename failed for %s: %v\n", path, err)
		_ = os.Remove(tmp)
	}
}

func patchPresetSkillsPathsMap(caps map[string]interface{}) bool {
	skillsRaw, hasSkills := caps["skills"]
	if !hasSkills {
		caps["skills"] = map[string]interface{}{"paths": append([]interface{}{}, defaultPresetSkillsPaths...)}
		return true
	}
	skillsCfg, ok := skillsRaw.(map[string]interface{})
	if !ok {
		return false
	}
	if _, hasPaths := skillsCfg["paths"]; hasPaths {
		return false
	}
	skillsCfg["paths"] = append([]interface{}{}, defaultPresetSkillsPaths...)
	return true
}
